---
openapi: 3.0.3
components:
  headers:
    Etag:
      description: |-
        [RFC 9110 - 8.8.3 Etag](https://www.rfc-editor.org/rfc/rfc9110.html#name-etag).
        The general purpose Etag.
      schema:
        $ref: "#/components/schemas/Etag"
  responses:
    Problem:
      description: Problem Response
      headers:
        Etag:
          $ref: "#/components/headers/Etag"
      content:
        application/problem+json:
          schema:
             $ref: "#/components/schemas/Problem"
  schemas:
    Etag:
      type: string
      description: |-
        [RFC 9110 - 8.8.3 Etag](https://www.rfc-editor.org/rfc/rfc9110.html#name-etag).
        The general purpose Etag.
    Id:
      type: string
      format: uuid
    Problem:
      type: object
      description: |-
        Problem according to [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457.html).
      required:
        - type
        - title
        - status
      properties:
        type:
          type: string
          format: uri-reference
          description: |-
            A URI reference that identifies the problem type.
            Take a look [RFC 9457 - 3.1.1 "type"](https://www.rfc-editor.org/rfc/rfc9457.html#name-type).
        title:
          type: string
          description: A short, human-readable summary of the problem type.
        status:
          type: integer
          format: int32
          description: The HTTP system code generated by the origin server for this occurrence of the problem.
          maximum: 599
          minimum: 100
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
        instance:
          type: string
          format: uri-reference
          description: A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
